# Generated by Django 5.2.1 on 2025-06-03 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='parentCategory',
        ),
    ]
