# Generated by Django 5.2.1 on 2025-06-02 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_usermodel_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('parentCategory', models.ForeignKey(blank=True, db_column='parentCategory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='base.categorymodel')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='base.categorymodel'),
        ),
    ]
