# Generated by Django 5.2.1 on 2025-06-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_productmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Customer's wallet balance (only used for customer role)", max_digits=10),
        ),
    ]
