# Generated by Django 5.2.1 on 2025-06-03 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_orderitemmodel_ordermodel_orderitemmodel_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='products',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='total',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(default='processing', max_length=32),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base.ordermodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.productmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderItemModel',
        ),
    ]
