# Generated by Django 5.2.1 on 2025-06-04 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_usermodel_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('in_transit', 'In_Transit'), ('out_for_delivery', 'Out_For_Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('carrier', models.CharField(default='AWE Express', max_length=100)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='base.ordermodel')),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
    ]
