# Generated by Django 5.2.1 on 2025-06-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_shoppingcartmodel_cartitemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_address',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_city',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_full_name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_postal_code',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
    ]
